# PY-ASCII
ASCII converter


#currently have issues with the PIL.Image.open(path)
#image.size cant be ID
